# -*- coding: utf-8 -*-
"""sentimental_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kp1AoDA7dxAYs9BY9-manSDC2WFs1tOq

# ***sentimental analysis using imdb datasets***
"""

#impporting libraries
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import LSTM,Dense
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence



#loading imdb dataset
(xtrain,ytrain),(xtest,ytest)=imdb.load_data(num_words=6000)

#padding train and test data
xtrain=sequence.pad_sequences(xtrain,maxlen=500)
xtest=sequence.pad_sequences(xtest,maxlen=500)

#creating model
model=Sequential()
model.add(Embedding(6000,32,input_length=500))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))

"""compiling model"""

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

"""Fitting our compiled **model**
to our training set
"""

model.fit(xtrain,ytrain,epochs=10,batch_size=64)
#print(xtest)

model_accuracy = model.evaluate(xtest, ytest, verbose=0)

print("Model accuracy on the test dataset: {0:.2f}%".format(model_accuracy[1]*100))

